name = "webapp"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "webapp-production"
database_id = "placeholder-database-id"

[env.production]
name = "webapp"